[assembly: System.Reflection.AssemblyCompany("Jesper Åström")]
[assembly: System.Reflection.AssemblyProduct("FluidMvc")]
[assembly: System.Reflection.AssemblyCopyright("Copyright ©  2013")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyVersion("0.0.0.1")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.0.1")]